server:
  port: 8848
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf-8
      username: root
      password: root
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      filters: stat,log4j2
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
    password:
    key-prefix: zgl-
    command-timeout: 2s
    default-ttl: 60s
    ttl:
      getEmpAuth: 1800s
    lettuce:
      pool:
        max-active: 100
        max-wait: 500ms
        max-idle: 500
        min-idle: 0
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 20s
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.zgl.springboot.domain
  global-config:
    db-config:
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'



